[functions.create-checkout]
verify_jwt = true

[functions.register-affiliate]
verify_jwt = true

[functions.mercado-pago-webhook]
verify_jwt = false

[functions.create-test-checkout]
verify_jwt = false

[functions.create-order]
verify_jwt = true
